version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    networks:
      - microservices-net

  data-service:
    build: ./data-service
    container_name: data-service
    ports:
      - "5002:5002"
    networks:
      - microservices-net

  logging-service:
    build: ./logging-service
    container_name: logging-service
    ports:
      - "5003:5003"
    networks:
      - microservices-net

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

